module.exports = {
    //需要权限访问
    authPath:[
        "apps",
        "user"
    ],
    //需要权限ajax访问
    authAjaxPath:[
        "get",
        "post",
        "put",
        "options",
        "head",
        "delete"
    ],
    //不需要权限ajax访问
    unauthAjaxPath:[
        "_get",
        "_post",
        "_put",
        "_options",
        "_head",
        "_delete",
        "_login",
        "_register"
    ],
    //不需要权限访问
    unauthPath:[
        "",
        "_logout",
        "_apps",
        "_user",
        '_snippets',
        '_logs'
    ],
    //静态文件路径
    staticPath:[
        "public",
        "lib",
        "source"
    ]
};
