module.exports = {
    //需要权限访问
    authPath:[
        "apps",
        "user"
    ],
    //需要权限ajax访问
    authAjaxPath:[
        "get",
        "post",
        "put",
        "options",
        "head",
        "delete"
    ],
    //不需要权限ajax访问
    unauthAjaxPath:[
        "_get",
        "_post",
        "_put",
        "_options",
        "_head",
        "_delete"
    ],
    //不需要权限访问
    unauthPath:[
        "",
        "login",
        "logout",
        "register",
        "_apps",
        "_user"
    ],
    //静态文件路径
    staticPath:[
        "public",
        "lib"
    ]
};
